--- !silvertine.PlotGroup
name: location
section: location
title: Location
description: '

Earthquake location
  '
formats:
- !silvertine.PDF {}
variant: default
feather_icon: check
size_cm:
- 21.0
- 14.9
items:
- !silvertine.PlotItem
  name: location
  attributes: {}
  description: '


    '
