--- !silvertine.PlotCollection
group_refs:
- - shakemap
  - default
- - location
  - default
- - waveforms
  - default
- - fits_waveform
  - default
- - hudson
  - default
- - fits_waveform_ensemble
  - default
- - location_mt
  - default
- - seismic_stations
  - default
- - sequence
  - default
