--- !silvertine.PlotGroup
name: waveforms
section: waveforms
title: waveforms
description: '

Waveforms
  '
formats:
- !silvertine.PDF {}
variant: default
feather_icon: check
size_cm:
- 21.0
- 14.9
items:
- !silvertine.PlotItem
  name: waveforms_1
  attributes: {}
  description: ''
- !silvertine.PlotItem
  name: waveforms_2
  attributes: {}
  description: ''
- !silvertine.PlotItem
  name: waveforms_3
  attributes: {}
  description: ''
